//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from LPC.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace LithosNet.Compiler.Ast {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ILPCListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class LPCBaseListener : ILPCListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] LPCParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] LPCParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.topLevelDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTopLevelDecl([NotNull] LPCParser.TopLevelDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.topLevelDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTopLevelDecl([NotNull] LPCParser.TopLevelDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.inheritDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInheritDecl([NotNull] LPCParser.InheritDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.inheritDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInheritDecl([NotNull] LPCParser.InheritDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.typeSpec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeSpec([NotNull] LPCParser.TypeSpecContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.typeSpec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeSpec([NotNull] LPCParser.TypeSpecContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.varDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDecl([NotNull] LPCParser.VarDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.varDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDecl([NotNull] LPCParser.VarDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.paramList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParamList([NotNull] LPCParser.ParamListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.paramList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParamList([NotNull] LPCParser.ParamListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.funcDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncDecl([NotNull] LPCParser.FuncDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.funcDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncDecl([NotNull] LPCParser.FuncDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] LPCParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] LPCParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] LPCParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] LPCParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.ifStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStmt([NotNull] LPCParser.IfStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.ifStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStmt([NotNull] LPCParser.IfStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.whileStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStmt([NotNull] LPCParser.WhileStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.whileStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStmt([NotNull] LPCParser.WhileStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.switchStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchStmt([NotNull] LPCParser.SwitchStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.switchStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchStmt([NotNull] LPCParser.SwitchStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.switchBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchBlock([NotNull] LPCParser.SwitchBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.switchBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchBlock([NotNull] LPCParser.SwitchBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.caseBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaseBlock([NotNull] LPCParser.CaseBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.caseBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaseBlock([NotNull] LPCParser.CaseBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.defaultBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefaultBlock([NotNull] LPCParser.DefaultBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.defaultBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefaultBlock([NotNull] LPCParser.DefaultBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.breakStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreakStmt([NotNull] LPCParser.BreakStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.breakStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreakStmt([NotNull] LPCParser.BreakStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.returnStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStmt([NotNull] LPCParser.ReturnStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.returnStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStmt([NotNull] LPCParser.ReturnStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.exprStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprStmt([NotNull] LPCParser.ExprStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.exprStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprStmt([NotNull] LPCParser.ExprStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] LPCParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] LPCParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.assignmentExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentExpr([NotNull] LPCParser.AssignmentExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.assignmentExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentExpr([NotNull] LPCParser.AssignmentExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.logicalOrExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalOrExpr([NotNull] LPCParser.LogicalOrExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.logicalOrExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalOrExpr([NotNull] LPCParser.LogicalOrExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.logicalAndExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalAndExpr([NotNull] LPCParser.LogicalAndExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.logicalAndExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalAndExpr([NotNull] LPCParser.LogicalAndExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.equalityExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqualityExpr([NotNull] LPCParser.EqualityExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.equalityExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqualityExpr([NotNull] LPCParser.EqualityExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.relationalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalExpr([NotNull] LPCParser.RelationalExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.relationalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalExpr([NotNull] LPCParser.RelationalExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.additiveExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditiveExpr([NotNull] LPCParser.AdditiveExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.additiveExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditiveExpr([NotNull] LPCParser.AdditiveExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.multiplicativeExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicativeExpr([NotNull] LPCParser.MultiplicativeExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.multiplicativeExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicativeExpr([NotNull] LPCParser.MultiplicativeExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.unaryExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryExpr([NotNull] LPCParser.UnaryExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.unaryExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryExpr([NotNull] LPCParser.UnaryExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.postfixExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostfixExpr([NotNull] LPCParser.PostfixExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.postfixExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostfixExpr([NotNull] LPCParser.PostfixExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.argList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgList([NotNull] LPCParser.ArgListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.argList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgList([NotNull] LPCParser.ArgListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.primaryExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimaryExpr([NotNull] LPCParser.PrimaryExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.primaryExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimaryExpr([NotNull] LPCParser.PrimaryExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.arrayLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayLiteral([NotNull] LPCParser.ArrayLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.arrayLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayLiteral([NotNull] LPCParser.ArrayLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.mappingLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMappingLiteral([NotNull] LPCParser.MappingLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.mappingLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMappingLiteral([NotNull] LPCParser.MappingLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.foreachStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForeachStmt([NotNull] LPCParser.ForeachStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.foreachStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForeachStmt([NotNull] LPCParser.ForeachStmtContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace LithosNet.Compiler.Ast
