//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from LPC.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace LithosNet.Compiler.Ast {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="LPCParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ILPCListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] LPCParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] LPCParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.topLevelDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTopLevelDecl([NotNull] LPCParser.TopLevelDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.topLevelDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTopLevelDecl([NotNull] LPCParser.TopLevelDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.inheritDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInheritDecl([NotNull] LPCParser.InheritDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.inheritDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInheritDecl([NotNull] LPCParser.InheritDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.typeSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeSpec([NotNull] LPCParser.TypeSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.typeSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeSpec([NotNull] LPCParser.TypeSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDecl([NotNull] LPCParser.VarDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDecl([NotNull] LPCParser.VarDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamList([NotNull] LPCParser.ParamListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamList([NotNull] LPCParser.ParamListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.funcDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncDecl([NotNull] LPCParser.FuncDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.funcDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncDecl([NotNull] LPCParser.FuncDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] LPCParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] LPCParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] LPCParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] LPCParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.ifStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStmt([NotNull] LPCParser.IfStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.ifStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStmt([NotNull] LPCParser.IfStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.whileStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStmt([NotNull] LPCParser.WhileStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.whileStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStmt([NotNull] LPCParser.WhileStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStmt([NotNull] LPCParser.ReturnStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStmt([NotNull] LPCParser.ReturnStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.exprStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprStmt([NotNull] LPCParser.ExprStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.exprStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprStmt([NotNull] LPCParser.ExprStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] LPCParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] LPCParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.assignmentExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentExpr([NotNull] LPCParser.AssignmentExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.assignmentExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentExpr([NotNull] LPCParser.AssignmentExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.logicalOrExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOrExpr([NotNull] LPCParser.LogicalOrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.logicalOrExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOrExpr([NotNull] LPCParser.LogicalOrExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.logicalAndExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalAndExpr([NotNull] LPCParser.LogicalAndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.logicalAndExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalAndExpr([NotNull] LPCParser.LogicalAndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.equalityExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityExpr([NotNull] LPCParser.EqualityExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.equalityExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityExpr([NotNull] LPCParser.EqualityExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.relationalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExpr([NotNull] LPCParser.RelationalExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.relationalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExpr([NotNull] LPCParser.RelationalExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.additiveExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpr([NotNull] LPCParser.AdditiveExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.additiveExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpr([NotNull] LPCParser.AdditiveExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.multiplicativeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpr([NotNull] LPCParser.MultiplicativeExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.multiplicativeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpr([NotNull] LPCParser.MultiplicativeExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.unaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpr([NotNull] LPCParser.UnaryExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.unaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpr([NotNull] LPCParser.UnaryExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.postfixExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfixExpr([NotNull] LPCParser.PostfixExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.postfixExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfixExpr([NotNull] LPCParser.PostfixExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgList([NotNull] LPCParser.ArgListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgList([NotNull] LPCParser.ArgListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.primaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpr([NotNull] LPCParser.PrimaryExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.primaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpr([NotNull] LPCParser.PrimaryExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.arrayLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayLiteral([NotNull] LPCParser.ArrayLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.arrayLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayLiteral([NotNull] LPCParser.ArrayLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LPCParser.mappingLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMappingLiteral([NotNull] LPCParser.MappingLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LPCParser.mappingLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMappingLiteral([NotNull] LPCParser.MappingLiteralContext context);
}
} // namespace LithosNet.Compiler.Ast
