//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from LPC.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace LithosNet.Compiler.Ast {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="LPCParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ILPCVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] LPCParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.topLevelDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTopLevelDecl([NotNull] LPCParser.TopLevelDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.inheritDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInheritDecl([NotNull] LPCParser.InheritDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.typeSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeSpec([NotNull] LPCParser.TypeSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDecl([NotNull] LPCParser.VarDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamList([NotNull] LPCParser.ParamListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.funcDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncDecl([NotNull] LPCParser.FuncDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] LPCParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] LPCParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.ifStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStmt([NotNull] LPCParser.IfStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.whileStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStmt([NotNull] LPCParser.WhileStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.switchStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchStmt([NotNull] LPCParser.SwitchStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.switchBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchBlock([NotNull] LPCParser.SwitchBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.caseBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseBlock([NotNull] LPCParser.CaseBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.defaultBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefaultBlock([NotNull] LPCParser.DefaultBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.breakStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakStmt([NotNull] LPCParser.BreakStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStmt([NotNull] LPCParser.ReturnStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.exprStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprStmt([NotNull] LPCParser.ExprStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] LPCParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.assignmentExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentExpr([NotNull] LPCParser.AssignmentExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.logicalOrExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalOrExpr([NotNull] LPCParser.LogicalOrExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.logicalAndExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalAndExpr([NotNull] LPCParser.LogicalAndExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.equalityExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualityExpr([NotNull] LPCParser.EqualityExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.relationalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalExpr([NotNull] LPCParser.RelationalExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.additiveExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpr([NotNull] LPCParser.AdditiveExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.multiplicativeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeExpr([NotNull] LPCParser.MultiplicativeExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.unaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpr([NotNull] LPCParser.UnaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.postfixExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfixExpr([NotNull] LPCParser.PostfixExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgList([NotNull] LPCParser.ArgListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.primaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpr([NotNull] LPCParser.PrimaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.arrayLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayLiteral([NotNull] LPCParser.ArrayLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.mappingLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMappingLiteral([NotNull] LPCParser.MappingLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LPCParser.foreachStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForeachStmt([NotNull] LPCParser.ForeachStmtContext context);
}
} // namespace LithosNet.Compiler.Ast
